[wip] Py panel timeline example
voxel51/fiftyone-plugins pull request #166
Opened 2024-09-25 00:28 UTC by ritch

2024-09-25 00:28 UTC, ritch commented on plugins/panel-examples/__init__.py
> +    def on_click(self, ctx):
need to remove - this is unrelated to timeline

2024-09-25 00:29 UTC, ritch commented on plugins/panel-examples/__init__.py
> +class MyAnimatedPanel(foo.Panel):
Review this class

2024-10-22 05:19 UTC, brimoor commented
@ritch I pushed an update to get video-as-frames working (added example code to the PR description for testing) 💪 

Dynamic group playback works as expected when navigation is set to "video" mode. However, in "pagination" mode it looks like the label count panel is not re-rendering when the current frame is updated in VaF Looker. See the attached video for example. Can you take a look? 

Can you also fix the margins on the plot? There are a few issues:
- field selector dropdown is clipped by top of panel
- x axis label is clipped by bottom of panel
- both of above cause there to be a persistent scrollbar on the right

https://github.com/user-attachments/assets/2016d913-d8fb-4ad4-b354-ca0deb9faa1b

2024-10-22 05:39 UTC, ritch commented
> field selector dropdown is clipped by top of panel

Fixed in https://github.com/voxel51/fiftyone/pull/4956

2024-10-22 05:41 UTC, ritch commented
> x axis label is clipped by bottom of panel
> scrollbars

Will need @imanjra to take a look at these.

2024-10-22 05:44 UTC, ritch commented
> However, in "pagination" mode it looks like the label count panel is not re-rendering when the current frame is updated in VaF Looker

I think the issue is that the timeline api is not implemented for this mode. Will follow up with @sashankaryal.

2024-10-22 05:44 UTC, ritch commented
> I pushed an update to get video-as-frames working (added example code to the PR description for testing) 💪

Awesome 🙏 !!

2024-10-22 15:12 UTC, ritch commented
> it looks like the label count panel is not re-rendering when the current frame is updated in VaF Looker.

The pagination UI renders an ImageLooker and the frame number is not based on the `Timeline` api.

2024-11-12 16:55 UTC, sashankaryal requested changes

2024-11-12 16:55 UTC, sashankaryal commented on plugins/label_count/__init__.py
> +            reload_on_navigation=True,
this won't work

2024-11-26 22:24 UTC, sashankaryal approved these changes
lgtm! need to address navigation problem in a separate PR

2024-11-26 22:25 UTC, merged